# https://github.com/sympy/sympy/blob/master/.travis.yml
# https://github.com/codecov/example-python
# https://docs.travis-ci.com
# https://stackoverflow.com/a/3237883
# https://stackoverflow.com/a/5688592

language: python

before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install pytest-cov codecov awscli

install:
  - pip install .

script:
  # For testing, we want to limit downloads from the resource servers, and we
  # achieve this by the following:
  # 1) assign each job an ID
  # 2) select (identify) one of the jobs based on week of the year
  # 3) limit downloading of resources to selected job on master branch
  # 4) use cached resources on Amazon S3 for all other jobs
  # Note that the master branch is tested weekly via `cron`, so this ensures
  # all Python versions will be periodically integration tested with the
  # resource servers.
  - set -e
  - NUM_JOBS=3
  - SELECTED_JOB=$(($(date +%V) % $NUM_JOBS))
  - |
    if [ $TRAVIS_BRANCH == "master" ]; then
      if [ $SELECTED_JOB != $JOB_ID ]; then
        aws s3 cp s3://lineage-resources/resources.tar.gz resources.tar.gz
      fi
    else
      aws s3 cp s3://lineage-resources/resources.tar.gz resources.tar.gz
    fi
  - |
    if [ -f resources.tar.gz ]; then
      tar -xzf resources.tar.gz
      rm resources.tar.gz
    fi
  - pytest --cov=src tests
  - |
    if [ $SELECTED_JOB == $JOB_ID ]; then
      codecov
    fi

stages:
  - check formatting
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: check formatting
      python: 3.6
      before_install:
        - pip install black
      script:
        - black --check --diff .
    - stage: test
      python: 3.5
      env: JOB_ID=0
    - python: 3.6
      env: JOB_ID=1
    - python: 3.7
      dist: xenial
      env: JOB_ID=2
    - stage: deploy
      python: 3.6
      script: skip
      deploy:
        - provider: pypi
          user: "apriha"
          password:
            secure: "ILDxck7IPSffABa4mWFANETAOJgazxXJRJBFoMQ+0TKxsrTKVA6VDtrUBEAgxAdm2Zp9Lwh8vsOKodEToTrcm5J4JmnFsyz+pxBbPNpKE1RU4bn+X0qqd3D//iK6DoATxrQCS73MZA7GoMOEL7dvU2R8d2d8i6H3x4lDCIp3dcPRZm1+YYGo51bwv6MYJGcN9lQOtQlVgFYPp/9TSAiwK5sWjQk8Bfv7ASIJWGb0+oLW5AK468ANk1agof+pg56d041vWYDqTBuuaZs6gEYxJQSk0V0o896NoNoqenfIch39KeHnL4jTBUhftDk/NNT/wGfi8JasGC/ks+ESE7R8BwbWYb0QH9AhBQSraAjIr0IEyoOXYYl2FlghHWFC2/mBKZcmQXuL+Dx6tJxvAP914bB2sb+ZNNcBfuPkfzeOYoVosTly/O/MPoyuj2/Ohmw76hKzeGu2IE4UILQUsggaZvgVk/A+Vu8KmeOx15X+IgHn3ahJ3550K4d5vFTRlvY1EZQP5XY5Mx7OW55Orm71wZKOMIN4Y6COyZA7NCs0tCR5M7EjIk/j401Dm/O75hcYIY0J69eZiifSIXUNsJ+6QmOvhZJA8ZtYNlJ6nyGhBAF22a6wp7E2OQEY2WR2X1ZMRaP9SSr7X8wUbKHTt9JbEVFQwqTQzqdP+8Szj/Hh0nA="
          distributions: "sdist bdist_wheel"
          on:
            branch: master
            tags: true
